zurichat/zc_plugin_tools

- src/pages/index.js
Reverts zurichat/zc_plugin_tools#229
> Revert "Test for ci / cd again"

- src/pages/index.js
#231 is the issue I worked on.
View on
[https://zc-plugin-tools.vercel.app/](https://zc-plugin-tools.vercel.app/)
> Add giphy search box

- package.json
- public/index.html
- public/zurichatlogo.svg
- src/App.js
- src/components/MainPage.js
- src/components/MainPage/MainPage.js
- src/components/layout/index.js
- src/data/tools.data.js
- src/index.css
- tailwind.config.js
- yarn.lock
I kind of mimicked the Zuri main sidebar so that everyone can have a good idea of what the final will look like when building their part of the project
Team HOBBIES lets gooooooo!!!!!!
> Development update with the plain skeleton template

- .github/workflows/deploy.yml
- client/public/index.html
- client/src/index.css
- server/package.json
Lato Font family was added with different font size variations and was set up properly.
Preview at https://zc-plugin-tools-nine.vercel.app/
> Added original Font Family

- server/app.js
- server/package.json
- server/src/config/swagger.js
- server/src/controllers/giphy.js
- server/src/controllers/plugin-info.js
- server/src/docs/a.yml
- server/src/docs/b.yml
- server/src/docs/c.yml
- server/src/docs/d.yml
- server/src/docs/e.yml
- server/src/docs/f.yml
- server/src/docs/info.yml
- server/src/routes/giphy.js
- server/src/routes/index.js
- server/yarn.lock
Issue: https://github.com/zurichat/zc_plugin_tools/issues/267
Link for plugin info - https://externaltools.zuri.chat/api/info
Link for trending gifs - https://externaltools.zuri.chat/api/giphy/trending
Link for random gifs - https://externaltools.zuri.chat/api/giphy/random
Also, I set up documentation for endpoints using swagger
> Added a route to return Plugin information and added endpoints to return trending and random gifs

- server/package.json
- server/src/config/env.js
- server/src/routes/googledrive/index.js
- server/yarn.lock
**Before submitting your PR for review**
- Run `npm run eslint` to find errors in code syntax/format
- Run `npm run eslint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands
- Ensure you fix all merge conflicts before sending PR
Updates route format or google drive info endpoint
> updated google drive info route

- client/src/components/Apps/Figma/Figma.js
- client/src/components/Apps/Figma/about-secttion/FigmaAbout.js
- client/src/components/Apps/Figma/css/about.css
- client/src/components/searchbar.component.js
- Issue #350 
- To help the users understand the importance of installing Figma plugin in Zuri Chat.
- Preview Link [https://externaltools.zuri.chat/figma](https://externaltools.zuri.chat/figma)
Melford
@00mikhael
> Add Figma About Page

- client/src/components/Apps/GoogleDrive/DownloadPage/DownloadPage.js
- client/src/components/Apps/GoogleDrive/GoogleDrive.js
- client/src/components/Apps/GoogleDrive/GoogleDrive.module.css
- client/yarn.lock
@oscar-ekeyekwu.
Have rearranged the google drive home page. I added a tab to display the download page instead of having it in it's own separate page.
> Google Drive: Rearranged the google drive page to include tab for download

- client/src/components/Apps/Figma/about-secttion/FigmaAbout.js
- client/src/components/Apps/Figma/css/about.css
- client/yarn.lock
Slack Name: Kokoh
Issue: #335 
Description: I added the screenshot section to complete the Figma about page.
Live Link: [preview link](https://zc-plugin-tools-hllz1ljck-kokohg.vercel.app/figma)
Reviewer: @hokagedemehin 
What issue does this fix? #335
> Feature: adding screenshot section to figma about page 

- client/src/components/Apps/Giphy/Giphy.js
- client/src/components/Apps/Giphy/description/Description.js
- client/src/components/Apps/Giphy/description/description.css
- client/src/components/Apps/Giphy/giphy.css
- client/src/components/Apps/Giphy/main-giphy-layout/MainGiphyLayout.js
- client/src/components/Apps/Giphy/main-giphy-layout/main-layout.css
Fixes #295 
Summarise the main tasks handled in the pull request
This PR describes the giphy plugin
- fork and clone the repo
- cd into client folder
- run yarn install from the client folder in your terminal
- run yarn start
- navigate to localhost:3000/giphy on your browser to view the result of this PR
**What is the link to the issue on Github?**
[Issue #295](https://github.com/zurichat/zc_plugin_tools/issues/295)
> giphy feat: created the giphy description tab

- client/src/components/Apps/Github/containers/GithubInstalled.js
- client/src/components/Apps/GoogleDrive/DownloadPage/DownloadPage.js
issue was already closed #382 
Description: Made the page responsive for mobile view
add @oscar-ekeyekwu for pr review
Live Link
https://externaltools.zuri.chat/
How should this be manually tested?
https://externaltools.zuri.chat/
> Made Google Drive Download page responsive

- client/src/components/Apps/GoogleDrive/Messages/Messages.js
- client/src/components/Apps/GoogleDrive/Messages/Messages.module.css
@oscar-ekeyekwu 
here's the link to test 
https://pensive-wescoff-542468.netlify.app/
> Google Drive: Made the messages page for google drive responsive for Team Hobbes

- client/src/components/Apps/GoogleDrive/Messages/Messages.module.css
@oscar-ekeyekwu 
here's the link to test 
https://competent-jang-3c0a89.netlify.app/
> corrected link color issue, Team hobbes

- server/src/controllers/googledrive/index.js
- server/src/routes/googledrive/index.js
**Before submitting your PR for review**
- Run `npm run eslint` to find errors in code syntax/format
- Run `npm run eslint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands
- Ensure you fix all merge conflicts before sending PR
Fixes #issue_number (replace issue_number with the issue number this PR solves)
Summarise the main tasks handled in the pull request
**Description of Task to be completed?**
Describe (in detail) what the task completed in the pull request does as per the relevant task
**How should this be manually tested?**
Give bullet point instructions on how to setup the code and test it manually (Assume no prior experience on JS or code) …
> Google Drive: implement endpoint to fetch data from zuri (using dummy data)

- server/src/controllers/googledrive/index.js
- server/src/routes/googledrive/index.js
Reverts zurichat/zc_plugin_tools#467
> Revert "Google Drive: implement endpoint to fetch data from zuri (using dummy data)"

- client/src/components/Apps/GoogleDrive/DownloadPage/DownloadPage.js
issue was already closed #382
Description: Made the page responsive for mobile view
add @00mikhael  for pr review
Live Link
https://externaltools.zuri.chat/
How should this be manually tested?
https://externaltools.zuri.chat/
> made google drive download page more responsive

- client/src/components/Apps/Figma/css/messages.css
- client/src/components/Apps/Figma/messages-section/FigmaMessages.js
[Issue #414 ](https://github.com/zurichat/zc_plugin_tools/issues/414)
I added the last section containing img, button and list of what you can use the figma plug in to do on zuri chat.
> Added the last section of the message tab

- client/src/components/ToolsViewPage/ToolsView.js
- client/src/components/fragments/tools/Tools.module.css
**What is the link to the issue on Github?**
[Issue #240](https://github.com/zurichat/zc_plugin_tools/issues/240)
> filter for both uppercase and lowercase input

- client/src/components/Apps/Figma/Figma.js
- client/src/components/Apps/Figma/about-secttion/FigmaAbout.js
- client/src/components/Apps/Figma/about-secttion/FigmaAbout.module.css
- client/src/components/Apps/Figma/about-secttion/MainContent.js
- client/src/components/Apps/Figma/about-secttion/Screenshots.js
- client/src/components/Apps/Figma/css/about.css
Completely redo the figma about page.
The previous work is not responsive and did not strictly adhere to the design made by the designers.
I redo the complete figma about page and made it responsive and paid attention to every details on the design provided by the designers.
Issue: #475 
@hokagedemehin
> Build pixel-perfect and responsive Figma about page

- client/src/components/fragments/tools/Tools.module.css
- client/yarn.lock
**Before submitting your PR for review**
- Run `npm run eslint` to find errors in code syntax/format
- Run `npm run eslint:fix` to fix all auto-fixable errors in source code and auto-format with prettier
- Ensure you fix any linting errors displayed after running any of the above commands
- Ensure you fix all merge conflicts before sending PR
Fixes #issue_number (replace issue_number with the issue number this PR solves)
Summarise the main tasks handled in the pull request
**Description of Task to be completed?**
Describe (in detail) what the task completed in the pull request does as per the relevant task
**How should this be manually tested?**
Give bullet point instructions on how to setup the code and test it manually (Assume no prior experience on JS or code) …
> changes to the tools images

- client/src/components/Apps/Gmail/Gmail.css
- client/src/components/Apps/Gmail/Gmail.js
- Make Gmail plugin layout responsive
- Add caret buttons on security & compliance page
Fixes #issue_number 
#285 
Summarise the main tasks handled in the pull request
I made the Gmail plugin responsive for all devices and also changed some class names that was similar with other plugins which was messing with the styles. 
**Description of Task to be completed?**
Merge PR
**How should this be manually tested?**
**What is the link to the issue on Github?**
[Issue #285 ](https://github.com/zurichat/zc_plugin_tools/issues/285)
Reviews @Davien21 @oscar-ekeyekwu @hokagedemehin
> Make Gmail page responsive

- client/src/components/MainPage/Instaledtoolssection.js
- client/src/components/MainPage/installedcard.js
Fix broken links on tools page. 
All installed tools now route to the tools directory.
@hokagedemehin please review. @Kehinded walked us through for the error fix
> Fix broken links on tools page
